apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: package-service
  template:
    metadata:
      labels:
        app: package-service
    spec:
      containers:
      - name: package-service
        image: your-dockerhub-username/package-service:latest
        ports:
        - containerPort: 5000
